--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4
-- Dumped by pg_dump version 17.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ops_propertylisting; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ops_propertylisting (
    id bigint NOT NULL,
    user_property_id integer NOT NULL,
    listing_type character varying(10) NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    price numeric(12,2) DEFAULT 0.00 NOT NULL
);


ALTER TABLE public.ops_propertylisting OWNER TO postgres;

--
-- Name: ops_propertylisting_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ops_propertylisting ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ops_propertylisting_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ops_propertyreviewrequest; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ops_propertyreviewrequest (
    id bigint NOT NULL,
    property_listing_id bigint NOT NULL,
    requester_id integer NOT NULL,
    status character varying(20) NOT NULL,
    comment text,
    requested_at timestamp with time zone NOT NULL
);


ALTER TABLE public.ops_propertyreviewrequest OWNER TO postgres;

--
-- Name: ops_propertyreviewrequest_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ops_propertyreviewrequest ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ops_propertyreviewrequest_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ops_purchaseagreement; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ops_purchaseagreement (
    id bigint NOT NULL,
    user_property_id integer NOT NULL,
    renter_id integer NOT NULL,
    start_date date NOT NULL,
    end_date date,
    transaction_id text NOT NULL,
    created_at timestamp with time zone NOT NULL
);


ALTER TABLE public.ops_purchaseagreement OWNER TO postgres;

--
-- Name: ops_purchaseagreement_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ops_purchaseagreement ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ops_purchaseagreement_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ops_rentalreview; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ops_rentalreview (
    id bigint NOT NULL,
    agreement_id bigint NOT NULL,
    tenant_review text,
    landlord_review text,
    created_at timestamp with time zone NOT NULL
);


ALTER TABLE public.ops_rentalreview OWNER TO postgres;

--
-- Name: ops_rentalreview_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ops_rentalreview ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ops_rentalreview_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: test_table; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.test_table (
    id integer NOT NULL,
    name character varying(100)
);


ALTER TABLE public.test_table OWNER TO postgres;

--
-- Name: test_table_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.test_table_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.test_table_id_seq OWNER TO postgres;

--
-- Name: test_table_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.test_table_id_seq OWNED BY public.test_table.id;


--
-- Name: test_table id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.test_table ALTER COLUMN id SET DEFAULT nextval('public.test_table_id_seq'::regclass);


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	core	0001_initial	2025-04-06 16:35:47.62542+00
7	core	0002_property_alter_user_created_at_and_more	2025-04-06 16:36:56.581302+00
8	core	0003_userproperty_verification_status	2025-04-06 16:37:27.211867+00
9	core	0004_remove_userproperty_verification_status	2025-04-06 16:37:27.224314+00
10	core	0005_userproperty_verification_status	2025-04-06 16:37:27.233968+00
11	core	0006_fix_verification_status	2025-04-06 16:37:27.245397+00
12	ops	0001_initial	2025-04-06 16:38:57.19893+00
\.


--
-- Data for Name: ops_propertylisting; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.ops_propertylisting (id, user_property_id, listing_type, is_active, created_at, price) FROM stdin;
1	5	rent	t	2025-04-11 17:13:18.367189+00	0.00
2	31	rent	t	2025-04-15 21:19:59.43224+00	0.00
3	32	rent	t	2025-04-15 21:38:34.421086+00	0.00
4	33	rent	t	2025-04-15 21:47:20.231635+00	0.00
5	34	rent	t	2025-04-15 21:56:32.957818+00	0.00
6	35	rent	t	2025-04-15 22:17:57.025956+00	0.00
7	36	rent	t	2025-04-15 22:23:47.49103+00	0.00
8	37	rent	t	2025-04-15 22:28:21.777632+00	0.00
9	38	rent	t	2025-04-15 22:48:39.080832+00	0.00
10	39	rent	t	2025-04-16 00:19:34.892353+00	1600.00
\.


--
-- Data for Name: ops_propertyreviewrequest; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.ops_propertyreviewrequest (id, property_listing_id, requester_id, status, comment, requested_at) FROM stdin;
\.


--
-- Data for Name: ops_purchaseagreement; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.ops_purchaseagreement (id, user_property_id, renter_id, start_date, end_date, transaction_id, created_at) FROM stdin;
\.


--
-- Data for Name: ops_rentalreview; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.ops_rentalreview (id, agreement_id, tenant_review, landlord_review, created_at) FROM stdin;
\.


--
-- Data for Name: test_table; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.test_table (id, name) FROM stdin;
\.


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 12, true);


--
-- Name: ops_propertylisting_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.ops_propertylisting_id_seq', 10, true);


--
-- Name: ops_propertyreviewrequest_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.ops_propertyreviewrequest_id_seq', 1, false);


--
-- Name: ops_purchaseagreement_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.ops_purchaseagreement_id_seq', 1, false);


--
-- Name: ops_rentalreview_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.ops_rentalreview_id_seq', 1, false);


--
-- Name: test_table_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.test_table_id_seq', 1, false);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: ops_propertylisting ops_propertylisting_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ops_propertylisting
    ADD CONSTRAINT ops_propertylisting_pkey PRIMARY KEY (id);


--
-- Name: ops_propertyreviewrequest ops_propertyreviewrequest_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ops_propertyreviewrequest
    ADD CONSTRAINT ops_propertyreviewrequest_pkey PRIMARY KEY (id);


--
-- Name: ops_purchaseagreement ops_purchaseagreement_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ops_purchaseagreement
    ADD CONSTRAINT ops_purchaseagreement_pkey PRIMARY KEY (id);


--
-- Name: ops_rentalreview ops_rentalreview_agreement_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ops_rentalreview
    ADD CONSTRAINT ops_rentalreview_agreement_id_key UNIQUE (agreement_id);


--
-- Name: ops_rentalreview ops_rentalreview_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ops_rentalreview
    ADD CONSTRAINT ops_rentalreview_pkey PRIMARY KEY (id);


--
-- Name: test_table test_table_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.test_table
    ADD CONSTRAINT test_table_pkey PRIMARY KEY (id);


--
-- Name: ops_propertyreviewrequest_property_listing_id_693aeb49; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ops_propertyreviewrequest_property_listing_id_693aeb49 ON public.ops_propertyreviewrequest USING btree (property_listing_id);


--
-- Name: ops_propertyreviewrequest ops_propertyreviewre_property_listing_id_693aeb49_fk_ops_prope; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ops_propertyreviewrequest
    ADD CONSTRAINT ops_propertyreviewre_property_listing_id_693aeb49_fk_ops_prope FOREIGN KEY (property_listing_id) REFERENCES public.ops_propertylisting(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ops_rentalreview ops_rentalreview_agreement_id_2b864c65_fk_ops_purch; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ops_rentalreview
    ADD CONSTRAINT ops_rentalreview_agreement_id_2b864c65_fk_ops_purch FOREIGN KEY (agreement_id) REFERENCES public.ops_purchaseagreement(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

