--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4
-- Dumped by pg_dump version 17.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: core_property; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.core_property (
    id bigint NOT NULL,
    title character varying(100) NOT NULL,
    property_type character varying(20) NOT NULL,
    description text NOT NULL,
    location character varying(150) NOT NULL,
    status character varying(20) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT valid_property_type CHECK (((property_type)::text = ANY ((ARRAY['1_bedroom'::character varying, '2_bedroom'::character varying, '3_bedroom'::character varying, '4_bedroom'::character varying, '5_bedroom'::character varying, 'gated_house'::character varying])::text[])))
);


ALTER TABLE public.core_property OWNER TO postgres;

--
-- Name: COLUMN core_property.location; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.core_property.location IS 'Enter the full address including street number, street name, city/town, and GPS coordinates if available.';


--
-- Name: core_property_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.core_property ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_property_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_propertydocument; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.core_propertydocument (
    id bigint NOT NULL,
    attachment character varying(100) NOT NULL,
    uploaded_at timestamp with time zone NOT NULL,
    user_property_id bigint NOT NULL
);


ALTER TABLE public.core_propertydocument OWNER TO postgres;

--
-- Name: core_propertydocument_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.core_propertydocument ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_propertydocument_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_propertyimage; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.core_propertyimage (
    id bigint NOT NULL,
    image character varying(100) NOT NULL,
    uploaded_at timestamp with time zone NOT NULL,
    is_active boolean NOT NULL,
    property_id bigint NOT NULL
);


ALTER TABLE public.core_propertyimage OWNER TO postgres;

--
-- Name: core_propertyimage_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.core_propertyimage ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_propertyimage_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.core_user (
    id bigint NOT NULL,
    firstname character varying(100) NOT NULL,
    lastname character varying(100) NOT NULL,
    email character varying(254) NOT NULL,
    phone_number character varying(15) NOT NULL,
    password_hash text NOT NULL,
    role character varying(25) NOT NULL,
    id_type character varying(50) NOT NULL,
    id_value character varying(100) NOT NULL,
    is_verified boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    last_login timestamp with time zone,
    is_active boolean NOT NULL
);


ALTER TABLE public.core_user OWNER TO postgres;

--
-- Name: core_userproperty; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.core_userproperty (
    id bigint NOT NULL,
    is_verified boolean NOT NULL,
    is_active boolean NOT NULL,
    transaction_hash text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    owner_id bigint NOT NULL,
    property_id bigint NOT NULL
);


ALTER TABLE public.core_userproperty OWNER TO postgres;

--
-- Name: core_userproperty_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.core_userproperty ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_userproperty_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.core_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_property core_property_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_property
    ADD CONSTRAINT core_property_pkey PRIMARY KEY (id);


--
-- Name: core_propertydocument core_propertydocument_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_propertydocument
    ADD CONSTRAINT core_propertydocument_pkey PRIMARY KEY (id);


--
-- Name: core_propertyimage core_propertyimage_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_propertyimage
    ADD CONSTRAINT core_propertyimage_pkey PRIMARY KEY (id);


--
-- Name: core_userproperty core_userproperty_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_userproperty
    ADD CONSTRAINT core_userproperty_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: core_property unique_location; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_property
    ADD CONSTRAINT unique_location UNIQUE (location);


--
-- Name: core_property unique_title_location; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_property
    ADD CONSTRAINT unique_title_location UNIQUE (title, location);


--
-- Name: core_user users_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_user
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- Name: core_user users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_user
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: core_propertydocument_user_property_id_a75326b0; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX core_propertydocument_user_property_id_a75326b0 ON public.core_propertydocument USING btree (user_property_id);


--
-- Name: core_propertyimage_property_id_86e80a6a; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX core_propertyimage_property_id_86e80a6a ON public.core_propertyimage USING btree (property_id);


--
-- Name: core_userproperty_owner_id_9f1ebde6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX core_userproperty_owner_id_9f1ebde6 ON public.core_userproperty USING btree (owner_id);


--
-- Name: core_userproperty_property_id_1bcf199c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX core_userproperty_property_id_1bcf199c ON public.core_userproperty USING btree (property_id);


--
-- Name: users_email_0ea73cca_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_email_0ea73cca_like ON public.core_user USING btree (email varchar_pattern_ops);


--
-- Name: core_propertydocument core_propertydocumen_user_property_id_a75326b0_fk_core_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_propertydocument
    ADD CONSTRAINT core_propertydocumen_user_property_id_a75326b0_fk_core_user FOREIGN KEY (user_property_id) REFERENCES public.core_userproperty(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_propertyimage core_propertyimage_property_id_86e80a6a_fk_core_property_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_propertyimage
    ADD CONSTRAINT core_propertyimage_property_id_86e80a6a_fk_core_property_id FOREIGN KEY (property_id) REFERENCES public.core_property(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_userproperty core_userproperty_owner_id_9f1ebde6_fk_core_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_userproperty
    ADD CONSTRAINT core_userproperty_owner_id_9f1ebde6_fk_core_user_id FOREIGN KEY (owner_id) REFERENCES public.core_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_userproperty core_userproperty_property_id_1bcf199c_fk_core_property_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_userproperty
    ADD CONSTRAINT core_userproperty_property_id_1bcf199c_fk_core_property_id FOREIGN KEY (property_id) REFERENCES public.core_property(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

