# Generated by Django 5.2 on 2025-04-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_property_alter_user_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproperty',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
