# Generated by Django 5.2 on 2025-04-19 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_documentaccessrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('property_owner', 'Property Owner'), ('property_seeker', 'Property Seeker'), ('land_commission_rep', 'Land Commission Rep'), ('sys_admin', 'System Admin')], max_length=25),
        ),
    ]
