# Generated by Django 5.2 on 2025-04-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_userproperty_verification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproperty',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
