# Generated by Django 5.2 on 2025-04-18 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_hash', models.CharField(max_length=64, unique=True)),
                ('previous_hash', models.CharField(max_length=64, null=True)),
                ('block_number', models.BigIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('property_id', models.IntegerField()),
                ('owner_id', models.IntegerField()),
                ('document_hash', models.CharField(max_length=64, null=True)),
                ('verified_by', models.IntegerField()),
                ('verification_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'ledger_block',
                'ordering': ['block_number'],
            },
        ),
    ]
