# Generated by Django 5.2 on 2025-04-19 22:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_alter_block_property_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_id', models.CharField(max_length=100, unique=True)),
                ('property_id', models.CharField(max_length=100)),
                ('owner_id', models.IntegerField()),
                ('contract_type', models.CharField(choices=[('ownership_verification', 'Ownership Verification'), ('ownership_transfer', 'Ownership Transfer')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('executed', 'Executed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('conditions', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('executed_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'ledger_smart_contract',
            },
        ),
        migrations.AlterField(
            model_name='block',
            name='block_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='block',
            name='current_hash',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='block',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='block',
            name='verification_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='verified_by',
            field=models.IntegerField(null=True),
        ),
    ]
