# Generated by Django 5.2 on 2025-04-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_create_smart_contract'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_id', models.CharField(max_length=64, unique=True)),
                ('property_id', models.CharField(max_length=100)),
                ('owner_id', models.IntegerField()),
                ('tenant_id', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('security_deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('terminated', 'Terminated'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('terms_conditions', models.JSONField(default=dict)),
                ('owner_signature', models.BooleanField(default=False)),
                ('tenant_signature', models.BooleanField(default=False)),
                ('signature_date_owner', models.DateTimeField(null=True)),
                ('signature_date_tenant', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('smart_contract_id', models.CharField(max_length=64, null=True)),
                ('payment_history', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'ledger_rental_agreement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='smartcontract',
            name='contract_type',
            field=models.CharField(choices=[('ownership_verification', 'Ownership Verification'), ('property_transfer', 'Property Transfer'), ('document_verification', 'Document Verification'), ('rental_agreement', 'Rental Agreement')], max_length=50),
        ),
    ]
