# Generated by Django 5.2 on 2025-05-12 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_rentalagreement_alter_smartcontract_contract_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.CharField(max_length=100)),
                ('current_owner_id', models.IntegerField()),
                ('new_owner_id', models.IntegerField()),
                ('transfer_date', models.DateTimeField(auto_now_add=True)),
                ('completion_date', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('transaction_hash', models.CharField(max_length=64, null=True)),
                ('transfer_reason', models.TextField()),
                ('transfer_amount', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('document_hash', models.CharField(max_length=64, null=True)),
            ],
            options={
                'db_table': 'property_transfer',
                'ordering': ['-transfer_date'],
            },
        ),
    ]
