# Generated by Django 5.2 on 2025-05-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0007_rentalrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalrequest',
            name='request_id',
            field=models.CharField(default='REQ_DEFAULT', max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
