# Generated by Django 5.2 on 2025-05-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0008_auto_20250512_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=64, unique=True)),
                ('property_id', models.CharField(max_length=100)),
                ('property_seeker_id', models.IntegerField()),
                ('owner_id', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('converted', 'Converted to Agreement')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('response_message', models.TextField(blank=True)),
                ('response_date', models.DateTimeField(null=True)),
                ('rental_agreement_id', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'ledger_rental_request',
                'ordering': ['-created_at'],
            },
        ),
    ]
